stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the project..."
    - test -f index.html || (echo "index.html not found!" && exit 1)
    - echo "Build successful!"

test_job:
  stage: test
  image: node:18  # 使用 Node.js 镜像运行测试工具
  script:
    - echo "Running tests..."
    - npm install -g htmlhint csslint eslint  # 安装静态代码检查工具
    - htmlhint index.html  # 检查 HTML 文件语法
    - csslint styles/  # 检查 CSS 文件语法（假设样式文件在 styles/ 文件夹中）
    - eslint scripts/  # 检查 JavaScript 文件语法（假设脚本文件在 scripts/ 文件夹中）
    - echo "All tests passed!"

deploy_job:
  stage: deploy
  image: alpine:latest  # 使用轻量级镜像
  script:
    - echo "Deploying project to GitLab Pages..."
    - mkdir -p public  # 创建 GitLab Pages 的部署目录
    - cp -r * public/  # 将所有项目文件复制到 public 目录
  artifacts:
    paths:
      - public  # 指定部署目录
  only:
    - main  # 仅在 main 分支执行部署
